manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cormoran
      url-base: https://github.com/cormoran
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3
      import: app/west.yml
    - name: zmk-feature-default-layer
      remote: cormoran
      revision: 92728246f80d327709839b2dbf5cf11880ff87e1
  self:
    path: config
